### Code of Distribution by Scipy python 
##### =======================
##### PMF, PDF,CDF 

In [1]:
# PMF: Probability of Mass function (That function discribe all probability of x value).
# PDF: Probability of density function (have x and you need y).
# CDF: Cumulative density function.
# PPF: percent point function (or inverse cumulative distribution function) returns x value that has a given CDF (y).
# SF: Survival function (SF): 1-CDF

### Import distribution from Scipy package

#### --> Import Discrete Distribution>--

In [2]:
# Import bernoulli distribution .
from scipy.stats import bernoulli

In [3]:
# Import Poisson Distribution.
from scipy.stats import poisson

In [4]:
# Import Binomial Distribution.
from scipy.stats import binom

In [5]:
# Import describe method from scipy to calculate var and mean.
from scipy.stats import describe

### Bernoulli Distribution Method.

In [6]:
# To create PMF for bernoulli Distribution.
# PMF have only two value at loc =(1-p), loc+1 = p, else equal zero.
PMF = bernoulli.pmf(k=1, p = 0.2, loc=0) # optional loc default = 0
PMF

0.2

In [7]:
# To create sample space of n trials = size, and p at loc+1.
RVS = bernoulli.rvs(p=0.4, loc=0, size=10, random_state=None)
RVS

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [8]:
# To get Cumulative distribution function.
# loc start point on x, p probability at x = loc+1, K is the x value that i want to calculate cdf for it.
CDF = bernoulli.cdf(k=2, p=0.3, loc=1)
CDF

1.0

In [9]:
# PPF use when i have y and i  need x, q is y value, p positive probability, loc that location.
PPF = bernoulli.ppf(q=0.4, p=0.6, loc=3)
PPF

3.0

In [10]:
# SF: Survival function (SF): 1-CDF, K is x value, p probablilty at loc+1, 
SF = bernoulli.sf(k=-1, p=0.7, loc=0)
SF

1.0

In [11]:
# calculate mean, median, variance, std by two way.
print(describe(PMF).mean)
print(describe(PMF).variance)
print(bernoulli.mean(p=0.2,loc=0))
print(bernoulli.median(p=0.2,loc=0))

0.2
nan
0.2
0.0


C:\Users\Mhmd Syd\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3583: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\Mhmd Syd\anaconda3\lib\site-packages\numpy\core\_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


### Binomial Distribution Method.

In [12]:
# To create PMF for Binomial Distribution.
# PMF_binom have (K=x value, n= number of trails, p probability at loc+1, loc inital location).
PMF_binom = binom.pmf(k=-1, n=2, p=0.4, loc=0)
PMF_binom

0.0

In [13]:
# To create sample space of trials = size, n=end value, loc= start value, p= probability of event True.
RVS_binom = binom.rvs(n=20, p=0.3, loc=1, size=10, random_state=None)
RVS_binom

array([ 8, 11,  2,  6,  8, 10,  6,  7,  7,  7])

In [14]:
# To get Cumulative distribution function for binomial distribution.
# K= x value, n=end value, p=probability, loc=start value.
CDF_binom = binom.cdf(k=5,n=10, p=(1.0/3), loc=0)
CDF_binom

0.9234364680180868

In [15]:
# PPF use when i have y and i  need x, q is y value, p positive probability, loc that location, n=end value.
PPF_binom = binom.ppf(q=0.4,n=10, p=0.6, loc=3)
PPF_binom

9.0

In [16]:
# SF: Survival function (SF): 1-CDF, K is x value, p probablilty at loc+1,n=end value, 
SF_binom = binom.sf(k=1,n=10, p=0.7, loc=0)
SF_binom

0.9998563141

In [17]:
# calculate mean, median, variance, std by two way for binomial distribution.
print(describe(PMF_binom).mean)
print(describe(PMF_binom).variance)
print(binom.mean(n=10, p=0.2, loc=0))
print(binom.median(n=10, p=0.2, loc=0))
print(binom.std(n=10, p=0.2, loc=0))
print(binom.var(n=10, p=0.2, loc=0))

0.0
nan
2.0
2.0
1.2649110640673518
1.6


### Poisson Distribution Method.

In [18]:
# To create PMF for poisson Distribution.
# PMF_poisson have (K=x value, mu=mean, loc inital location).
PMF_poisson = poisson.pmf(k=1, mu=0.2, loc=0)
PMF_poisson

0.1637461506155964

In [19]:
# To create sample space of trials = size, n=end value, loc= start value,mu= mean.
RVS_poisson = poisson.rvs(mu=0.4, loc=0, size=10, random_state=None)
RVS_poisson

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 1])

In [20]:
# To get Cumulative distribution function for poisson distribution.
# K= x value, mu=mean value, loc=start value.
CDF_poisson = poisson.cdf(k=1,mu=0.3, loc=0)
CDF_poisson

0.9630636868862332

In [21]:
# PPF use when i have y and i  need x, q is y value, mu=mean, loc that location.
PPF_poisson = poisson.ppf(q=0.999,mu=0.4, loc=0)
PPF_poisson

3.0

In [22]:
# SF: Survival function (SF): 1-CDF, K is x value, mu=mean, loc=start value.
SF_poisson = poisson.sf(k=1,mu=0.7, loc=0)
SF_poisson

0.1558049835546038

In [23]:
# calculate mean, median, variance, std by two way for poisson distribution.
print(describe(PMF_poisson).mean)
print(describe(PMF_poisson).variance)
print(poisson.mean(mu=0.4, loc=0))
print(poisson.median(mu=0.2, loc=0))
print(poisson.std(mu=0.4, loc=0))
print(poisson.var(mu=0.2, loc=0))

0.1637461506155964
nan
0.4
0.0
0.6324555320336759
0.2


#### --> Import Containous Distribution>--

In [24]:
# Import uniform distribution .
from scipy.stats import uniform

In [25]:
# Import normal distribution .
from scipy.stats import norm

In [26]:
# Import exponential distribution .
from scipy.stats import expon

### Uniform Distribution Method.


In [27]:
PDF_uniform = uniform.pdf(x=3, loc=0, scale=4)
PDF_uniform

0.25

In [28]:
# To create sample space of trials = size, scale=scale curve, loc= start value.
RVS_uniform = uniform.rvs(loc=0, scale=2, size=10, random_state=None)
RVS_uniform

array([0.73198474, 1.67539637, 0.90067893, 1.52648261, 0.85633772,
       1.3939456 , 0.08931455, 1.60030079, 1.87393284, 0.02689515])

In [29]:
# To get Cumulative distribution function for poisson distribution.
# K= x value, scale=scale curve value, loc=start value.
CDF_uniform = uniform.cdf(x=1, loc=0, scale=1)
CDF_uniform

1.0

In [30]:
# PPF use when i have y and i  need x, q is y value, scale=scale curve, loc that location.
PPF_uniform = uniform.ppf(q=0.68, loc=0, scale=1)
PPF_uniform

0.68

In [31]:
# SF: Survival function (SF): 1-CDF, K is x value, scale=scale curve, loc=start value.
SF_uniform = uniform.sf(x=0, loc=0, scale=1)
SF_uniform

1.0

In [32]:
# calculate mean, median, variance, std by two way for uniform distribution.
print(describe(PDF_uniform).mean)
print(describe(PDF_uniform).variance)
print(uniform.mean(loc=0, scale=1))
print(uniform.median(loc=0, scale=1))
print(uniform.std(loc=0, scale=1))
print(uniform.var(loc=0, scale=1))

0.25
nan
0.5
0.5
0.28867513459481287
0.08333333333333333


### Normal Distribution Method.

In [33]:
# PMF_poisson have (x=x value, scale=scale curve, loc inital location).
PDF_norm = norm.pdf(x=3, loc=0, scale=4)
PDF_norm

0.07528435803870111

In [34]:
# To create sample space of trials = size, n=end value, loc= start value,scale=scale curve.
RVS_norm = norm.rvs(loc=0, scale=2, size=10, random_state=None)
RVS_norm

array([-0.38878576, -3.30501032,  1.00293783,  0.86624196, -1.99781809,
        0.15050029, -1.37072668, -2.80363536,  0.05549269, -1.64518298])

In [35]:
# To get Cumulative distribution function for poisson distribution.
# K= x value, scale=scale curve value, loc=start value.
CDF_norm = norm.cdf(x=1, loc=0, scale=1)
CDF_norm

0.8413447460685429

In [36]:
# PPF use when i have y and i  need x, q is y value, scale=scale curve, loc that location.
PPF_norm= norm.ppf(q=0.68, loc=0, scale=1)
PPF_norm

0.4676987991145084

In [37]:
# SF: Survival function (SF): 1-CDF, K is x value, scale=scale curve, loc=start value.
SF_norm = norm.sf(x=0, loc=0, scale=1)
SF_norm

0.5

In [38]:
# calculate mean, median, variance, std by two way for uniform distribution.
print(describe(PDF_norm).mean)
print(describe(PDF_norm).variance)
print(norm.mean(loc=1, scale=3))
print(norm.median(loc=0, scale=1))
print(norm.std(loc=0, scale=2))
print(norm.var(loc=0, scale=1))

0.07528435803870111
nan
1.0
0.0
2.0
1.0


### Exponential Distribution Method.

In [39]:
# PMF_poisson have (x=x value, scale=scale curve, loc inital location).
PDF_expon = expon.pdf(x=3, loc=0, scale=4)
PDF_expon

0.11809163818525367

In [40]:
# To create sample space of trials = size, n=end value, loc= start value,scale=scale curve.
RVS_expon = expon.rvs(loc=0, scale=2, size=10, random_state=None)
RVS_expon

array([1.40443879, 1.3394783 , 0.26745927, 0.65610452, 1.60501285,
       0.84569989, 0.63442241, 0.2553493 , 3.91804627, 2.2940174 ])

In [41]:
# To get Cumulative distribution function for poisson distribution.
# K= x value, scale=scale curve value, loc=start value.
CDF_expon = expon.cdf(x=1, loc=0, scale=1)
CDF_expon

0.6321205588285577

In [42]:
# PPF use when i have y and i  need x, q is y value, scale=scale curve, loc that location.
PPF_expon= expon.ppf(q=0.68, loc=0, scale=1)
PPF_expon

1.139434283188365

In [43]:
# SF: Survival function (SF): 1-CDF, K is x value, scale=scale curve, loc=start value.
SF_expon = expon.sf(x=0, loc=0, scale=1)
SF_expon

1.0

In [44]:
# calculate mean, median, variance, std by two way for uniform distribution.
print(describe(PDF_expon).mean)
print(describe(PDF_expon).variance)
print(expon.mean(loc=1, scale=3))
print(expon.median(loc=0, scale=1))
print(expon.std(loc=0, scale=2))
print(expon.var(loc=0, scale=1))

0.11809163818525367
nan
4.0
0.6931471805599453
2.0
1.0
